### ISSUE TITLE
qBittorrent: headless depend from QT

### ISSUE THREAD

**Issue by UralZima** [rindeal/gentoo-overlay#163]
Hello. I want to build a headless qBittorrent. My use flags are only +webui, and it want bunch of QT4 packages. According to their readme, qt is not required in headless.

**Comment by rindeal** [comment]
Hello,

> According to their readme, qt is not required in headless.

I think you misread the readme (if not then report it to qtbittorrent maintainers as an issue), because it's not true it doesn't need any Qt. It only doesn't require GUI-related Qt packages like `dev-qt/qtgui` while it still needs `dev-qt/qtcore`, `dev-qt/qtnetwork`, ....

> My use flags are only +webui,

And also make sure you disable the `gui` USE-flag, which is set by default.

**Comment by UralZima** [comment]
Sorry, I found that qmake is used to build, so it seems it heavy rely on qt. -gui was disabled
Also, when I built on headless (with +webui +qt5), compile failed because of missing qtsingleapplication. After installing it, all went fine. It is not listed as dependent package, so you may check that and include it in depend section

**Comment by rindeal** [comment]
> Also, when I built on headless (with +webui +qt5), compile failed because of missing qtsingleapplication. After installing it, all went fine. It is not listed as dependent package, so you may check that and include it in depend section

You're right, will do. Thanks.
