### ISSUE TITLE
Failed to emerge sci-mathematics/mathematica-bin-11.0.1

### ISSUE THREAD

**Issue by mbbrinkman** [rindeal/gentoo-overlay#172]
Mathematica failed to emerge due to a sandbox violation 

Attached is my build.log 

[build.txt](https://github.com/rindeal/gentoo-overlay/files/1093669/build.txt)

**Comment by rindeal** [comment]
Quite challenging to find the culprit among those heaps of shitty shell scripts that make up the installer, but I finally found it and hopefully fixed.

For a reference:

1. `Mathematica_${PV}_LINUX.sh` is a Makeself script, which extracts from itself the real installer and a compressed archive with pre-compiled data.
2. the Makeself self-extractor itself is buggy and I needed some workarounds to make it stop after the extraction otherwise it would continue and executed the installer
3. then I thought that the infringing `mkdir -p` would be in the main installer script called `MathInstaller`, but after some debugging I found out that:
4. the `MathInstaller` script (after the extraction of data from the main archive) executes a function that tries to generate `.desktop` files, icons, ... and tries to install those files directly on the root fs to some hardcoded directories. The function also calls some other scripts (`xdg-*`, which it extracted earlier), which contain another set of hardcoded paths and try to do changes on the root fs as well.
5. one of those external scripts `xdg-desktop-menu` contained the well known error among shell scripts:

```sh
mkdir -p "${some_variable}/applications-merged"
```

without checking the variable first, which was apparently undefined and that triggered the sandbox warning

I'll push the fixed ebuild in a moment
