### ISSUE TITLE
Fix to handle URLs with tg:// protocol

### ISSUE THREAD

**Issue by jorgicio** [rindeal/gentoo-overlay#50]
Hi! Thanks for your contribution ;) However, I have experienced some issues at time of opening tg:// URLs, i.e., add channels or install stickers. I found the problem is in the .desktop file, so I tried a modification and worked.

So in your ebuild, you have to do some changes:

Line 250:
it must say ``"${EPREFIX}/usr/bin/${PN} -- %u"	# exec``

And in the line 256, it must say: ``'MimeType=application/x-xdg-protocol-tg;x-scheme-handler/tg;'``

I had to edit the .desktop by hand and it works!

Thank you.

**Comment by rindeal** [comment]
Hi @jorgicio,

thanks for reporting. I have never used this feature so could you please post some link against which I could test this?

`"${EPREFIX}/usr/bin/${PN} -- %u" # exec` might be the culprit, but I doubt that `application/x-xdg-protocol-tg;` is too. It was present in the .desktop file some time ago, but was removed upstream, because some guy reported that the specification was only draft by LXDE and has never been adopted by other DEs.

Here is the commit - https://github.com/rindeal/gentoo-overlay/commit/89d7af48a306c7a9937afa156abfffadac50f737

I'll probably stick to the upstream .desktop file and remove the generator from my ebuild. It was introduced a long time ago, because upstream didn't provide any at that time.

**Comment by jorgicio** [comment]
Sure: Here's my channel to test: https://telegram.me/jorgicioblog, and also I think the MimeType is the culprit. I think yes, the upstream .desktop might be the solution, meanwhile, I had to manually edit the generated one to try.

Tried in Firefox, Opera and Chrome.

**Comment by rindeal** [comment]
`--` was the issue and is fixed in the new version which I push later today
