### ISSUE TITLE
dev-qt/qt-telegram-static-5.6.0_p001001: configure failed: "Project ERROR: libsystemd-journal development package not found"

### ISSUE THREAD

**Issue by soredake** [rindeal/gentoo-overlay#69]
https://gist.github.com/soredake/c9f29f02756f40e76c84be5a3b41b83f

**Comment by rindeal** [comment]
1. Does it compile without distcc?
2. Does this command `pkg-config --exists libsystemd-journal && echo yes` output `yes`?

**Comment by soredake** [comment]
1. No, still failing
2. Outputs nothing

**Comment by rindeal** [comment]
Does `=dev-qt/qtcore-5.6.0` compile?

```
USE="systemd" ebuild <PATH_TO_MAIN_TREE>/dev-qt/qtcore/qtcore-5.6.0.ebuild compile clean
```

**Comment by soredake** [comment]
> >>> Source compiled.

**Comment by rindeal** [comment]
Well, the feature test for systemd fails, because `pkg-config --libs libsystemd-journal` is empty on your system.

This is the feature test - https://gist.github.com/rindeal/3dcff9b7c692d4610880ee2de4ec8fae
so try to compile it and if it fails post the error message.

Though it's weird that `=dev-qt/qtcore-5.6.0` compiles fine. Could you post the build log from that compilation too?

**Comment by soredake** [comment]
>This is the feature test - https://gist.github.com/rindeal/3dcff9b7c692d4610880ee2de4ec8fae
so try to compile it and if it fails post the error message.
Successfully compiled.
>Though it's weird that =dev-qt/qtcore-5.6.0 compiles fine. Could you post the build log from that compilation too?
https://transfer.sh/YxF6S/qtcorebuild.log

**Comment by rindeal** [comment]
```
 * Applying qtcore-5.5.1-libsystemd.patch ...
```

that's it.

I'll include it here and push shortly.
